# Generated by Django 6.0.4 on 2026-04-26 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("faculty", "Faculty"),
                            ("department", "Department"),
                            ("library", "Library"),
                            ("lab", "Lab"),
                            ("admin", "Admin"),
                            ("facility", "Facility"),
                            ("hostel", "Hostel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description", models.TextField()),
                ("image_url", models.URLField(max_length=500)),
                ("tags", models.JSONField(default=list)),
                ("departments", models.JSONField(default=list)),
                ("facilities", models.JSONField(default=list)),
                ("opening_hours", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_label", models.CharField(max_length=100)),
                ("start_time", models.CharField(max_length=100)),
                ("location_name", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("social", "Social"),
                            ("sports", "Sports"),
                            ("career", "Career"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="api.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("lost", "Lost"), ("found", "Found")], max_length=10
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("contact_hint", models.CharField(max_length=255)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost_items",
                        to="api.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("is_student", models.BooleanField(default=True)),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "year_of_study",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("has_completed_onboarding", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responses", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
